### ISSUE TITLE
ERROR Error: socket hang up

### ISSUE THREAD

**Issue by tatsuro-ueda** [hoo89/hubot-twitter-userstream#1]
このアダプタが便利そうだと思って、説明書通りインストールしたのですが、以下のようなエラーが出ます。もし何か対処法がありましたら教えて下さい。

```
[Sat Nov 15 2014 22:17:46 GMT+0900 (JST)] ERROR Error: socket hang up
  at SecurePair.error (tls.js:1013:23)
  at EncryptedStream.CryptoStream._done (tls.js:705:22)
  at CleartextStream.read [as _read] (tls.js:496:24)
  at CleartextStream.Readable.read (_stream_readable.js:320:10)
  at EncryptedStream.onCryptoStreamFinish (tls.js:301:47)
  at EncryptedStream.g (events.js:180:16)
  at EncryptedStream.EventEmitter.emit (events.js:117:20)
  at finishMaybe (_stream_writable.js:360:12)
  at endWritable (_stream_writable.js:367:3)
  at EncryptedStream.Writable.end (_stream_writable.js:345:5)
  at EncryptedStream.CryptoStream.end (tls.js:643:31)
  at Socket.onend (_stream_readable.js:482:10)
  at Socket.g (events.js:180:16)
  at Socket.EventEmitter.emit (events.js:117:20)
  at _stream_readable.js:919:16
  at process._tickCallback (node.js:419:13)

[Sat Nov 15 2014 22:17:46 GMT+0900 (JST)] ERROR Error: socket hang up
  at createHangUpError (http.js:1472:15)
  at CleartextStream.socketCloseListener (http.js:1522:23)
  at CleartextStream.EventEmitter.emit (events.js:117:20)
  at tls.js:696:10
  at process._tickCallback (node.js:419:13)

[Sat Nov 15 2014 22:17:46 GMT+0900 (JST)] ERROR Error: socket hang up
  at createHangUpError (http.js:1472:15)
  at CleartextStream.socketOnEnd [as onend] (http.js:1568:23)
  at CleartextStream.onCryptoStreamEnd (tls.js:320:24)
  at CleartextStream.g (events.js:180:16)
  at CleartextStream.EventEmitter.emit (events.js:117:20)
  at _stream_readable.js:919:16
  at process._tickCallback (node.js:419:13)
```

よろしくお願いします。

**Comment by tatsuro-ueda** [comment]
環境はRasbian / Raspberry Pi、Node.js 0.10.28です。

デフォルトの「> hubot ping」は「pong」が返ってきます。

**Comment by tatsuro-ueda** [comment]
エラーは出ているのですが動作しました。お騒がせしました。

**Comment by hoo89** [comment]
報告ありがとうございます。
対応が遅れてすみません。
こちらでは再現しなかったため、原因は推測するしか無いのですが…

> [Sat Nov 15 2014 22:17:46 GMT+0900 (JST)] ERROR Error: socket hang up
>  at SecurePair.error (tls.js:1013:23)

SSLを用いて接続を行う部分で例外が発生しているようです。
twitter-userstreamでは[twit](https://github.com/ttezel/twit)というライブラリを介してtwitterに接続していますが、どうやらその部分の問題のようです。

調べたところ似たようなエラーはいくつか他でも報告されています。
http://stackoverflow.com/questions/22544975/nodejs-https-error-socket-hang-up-with-localhost
https://github.com/gulpjs/gulp/issues/667

上ではTCPコネクションが予期せず閉じられた時に発生する例外(ECONNRESET)と説明されていました。

考えられる原因としては
- twitの不具合
- ネットワーク内の問題
- その他の依存ライブラリの不具合

等が挙げられます。

どれにしろ、twitより下の依存ライブラリにはノータッチという方針ですので、
こちらの問題ではなく、この問題へコード変更という形での対処は行わないと思います。
